[window]
padding = { x = 10, y = 10 }
opacity = 0.8

[font]
normal = { family = "GeistMono NF", style = "Bold" }
size = 13

[colors.primary]
foreground = "#cad3f5"
background = "#0b0c11"

[colors.normal]
black = "#000000"
red = "#FD788B"
green = "#20FF4F"
yellow = "#F4CC67"
blue = "#68A9FF"
magenta = "#F970CD"
cyan = "#39FFE2"
white = "#ffffff"

[mouse]
bindings = [
{ mouse = "Middle", action = "None" }
]
